#!/bin/bash

#SBATCH --time=48:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=96GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

python -m venv ../venv
source ../venv/bin/activate
pip install -r requirements.txt

python -u cnn-lstm.py --epochs 30 --dropout 0.5 --n_chunks 20 --lstm_input_size 64 --lstm_hidden_size 256