#!/bin/bash

#SBATCH --time=60:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=100GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../venv/bin/activate

python -u lstm_cnn_model.py --num_layers 1 --hidden_size 256 --epochs 30 --dropout 0
