#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=16GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../venv/bin/activate

python -u parallel_cnn_lstm.py --num_layers 2 --hidden_size 256 --epochs 400 --dropout 0.8