#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=16GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../venv/bin/activate

python -u res_densenet.py --epochs 50 --pretrain --model_name densenet_test_precision8_75_adadelta --feature_extract
