#!/bin/bash

#SBATCH --time=23:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=8GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../venv/bin/activate

python -u lstm.py --num_layers 2 --hidden_size 128 --epochs 300 --dropout 0.8
python -u lstm.py --num_layers 2 --hidden_size 256 --epochs 300 --dropout 0.8
python -u lstm.py --num_layers 2 --hidden_size 512 --epochs 300 --dropout 0.8
python -u lstm.py --num_layers 2 --hidden_size 1024 --epochs 300 --dropout 0.8
