#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=8GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../venv/bin/activate

python -u simple_dense_cnn.py --epochs 400 --block_config 2
python -u simple_dense_cnn.py --epochs 400 --block_config 1 1
python -u simple_dense_cnn.py --epochs 400 --block_config 3 3
python -u simple_dense_cnn.py --epochs 400 --block_config 4 4