#!/bin/bash

#SBATCH --time=20:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --mem=8GB

ml Python/3.6.4-foss-2018a
ml CUDA/9.1.85

source ../../venv/bin/activate

python -u ../second_lstm.py --num_layers=1 hidden_size=8
python -u ../second_lstm.py --num_layers=1 hidden_size=16
python -u ../second_lstm.py --num_layers=1 hidden_size=32
python -u ../second_lstm.py --num_layers=1 hidden_size=64
python -u ../second_lstm.py --num_layers=2 hidden_size=8
python -u ../second_lstm.py --num_layers=2 hidden_size=16
python -u ../second_lstm.py --num_layers=2 hidden_size=32
python -u ../second_lstm.py --num_layers=2 hidden_size=64